# Site settings
title: Pablo Corbalán
email: pablo.corbalan@cit.ie
description: Research, Networks, Contiki, Python, & Life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pablocorbalan.com"
github_username:  pablocorbalan
twitter_username: paulcorbalan

# Build settings
markdown: kramdown
permalink: /:title

# Author
author: Pablo Corbalan

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
