# Site settings
title: Pablo Corbalán
email: p.corbalanpelegrin(at)unitn.it
description: Networked Embedded Systems, Wireless Sensor Networks, and the Internet of Things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pablocorbalan.com"
github_username:  pablocorbalan
twitter_username: paulcorbalan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

# Author
author: Pablo Corbalan

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
